title: Daniel Butler
description: Automation Engineer at IBM Cloud | Making Cloud Development Easier
url: "https://dbdev.ie"
baseurl: ""

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: dark

# Enable or disable heading anchors
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2024 Daniel Butler."

# Enable or disable back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Aux links for the upper right navigation
aux_links:
  "VS Code IBM Catalog Editor":
    - "https://github.com/daniel-butler-irl/VS_Code_Catalog_Json_Editor"
  "GitHub Profile":
    - "https://github.com/daniel-butler-irl"

# Makes Aux links open in a new tab
aux_links_new_tab: true

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor