title: Daniel Butler
description: Automation Engineer at IBM Cloud | Making Cloud Development Easier
url: "https://dbdev.ie"
baseurl: ""

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author information
author:
  name: Daniel Butler
  email: daniel.butler.irl@gmail.com
  github: daniel-butler-irl
  linkedin: daniel-butler-1a525832

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/