source "https://rubygems.org"

gem "jekyll", "~> 3.9.3"
gem "just-the-docs"
gem "github-pages", group: :jekyll_plugins
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag"
  gem "jekyll-remote-theme"
end